// ZeroCore Agent — eBPF Userspace Loader
// Loads probe.bpf.o, attaches kprobes, reads ring buffer.
// Emits newline-delimited JSON to stdout — consumed by ebpf_bridge.py
// via subprocess pipe.
//
// Build:
//   go generate  (runs bpf2go to compile probe.bpf.c)
//   go build -o zerocore-probe .
//
// Run (requires CAP_BPF + CAP_PERFMON, or root):
//   ./zerocore-probe

//go:generate bpf2go -cc clang -cflags "-O2 -g -Wall -target bpf" Probe probe.bpf.c

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// ---------------------------------------------------------------------------
// ProcessFileEvent mirrors the C struct process_file_event exactly.
// Field sizes must match probe.bpf.c — validated at load time by CO-RE.
// ---------------------------------------------------------------------------
type ProcessFileEvent struct {
	EventType uint32
	PID       uint32
	PPID      uint32
	UID       uint32
	GID       uint32
	Comm      [16]byte
	FilePath  [256]byte
	Args      [128]byte
}

// EventJSON is the outbound schema written to stdout.
type EventJSON struct {
	Timestamp string `json:"timestamp"`
	EventType string `json:"event_type"` // "vfs_write" | "execve"
	PID       uint32 `json:"pid"`
	PPID      uint32 `json:"ppid"`
	UID       uint32 `json:"uid"`
	GID       uint32 `json:"gid"`
	Process   string `json:"process"`  // comm
	FilePath  string `json:"file_path"`
	Args      string `json:"args"`
}

const (
	eventVFSWrite uint32 = 1
	eventExecve   uint32 = 2
)

func nullTerminated(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}

func eventTypeName(t uint32) string {
	switch t {
	case eventVFSWrite:
		return "vfs_write"
	case eventExecve:
		return "execve"
	default:
		return "unknown"
	}
}

func parseEvent(raw []byte) (*EventJSON, error) {
	if len(raw) < int(unsafe.Sizeof(ProcessFileEvent{})) {
		return nil, fmt.Errorf("short read: %d bytes", len(raw))
	}

	ev := (*ProcessFileEvent)(unsafe.Pointer(&raw[0]))

	return &EventJSON{
		Timestamp: time.Now().UTC().Format(time.RFC3339Nano),
		EventType: eventTypeName(ev.EventType),
		PID:       ev.PID,
		PPID:      ev.PPID,
		UID:       ev.UID,
		GID:       ev.GID,
		Process:   nullTerminated(ev.Comm[:]),
		FilePath:  nullTerminated(ev.FilePath[:]),
		Args:      strings.TrimSpace(nullTerminated(ev.Args[:])),
	}, nil
}

func main() {
	// Remove kernel memory lock limit — required for eBPF map allocation
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("failed to remove memlock: %v", err)
	}

	// Load pre-compiled eBPF objects (generated by bpf2go from probe.bpf.c)
	objs := ProbeObjects{}
	if err := LoadProbeObjects(&objs, nil); err != nil {
		log.Fatalf("failed to load eBPF objects: %v\nEnsure BTF is available (/sys/kernel/btf/vmlinux)", err)
	}
	defer objs.Close()

	// Attach kprobe to vfs_write
	kpVfsWrite, err := link.Kprobe("vfs_write", objs.KprobeVfsWrite, nil)
	if err != nil {
		log.Fatalf("failed to attach kprobe/vfs_write: %v", err)
	}
	defer kpVfsWrite.Close()

	// Attach tracepoint to sys_enter_execve
	tpExecve, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TracepointExecve, nil)
	if err != nil {
		log.Fatalf("failed to attach tracepoint/sys_enter_execve: %v", err)
	}
	defer tpExecve.Close()

	// Open ring buffer reader
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		log.Fatalf("failed to open ring buffer: %v", err)
	}
	defer rd.Close()

	log.Printf("ZeroCore eBPF probe active — PID %d", os.Getpid())

	// Graceful shutdown on SIGINT / SIGTERM
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	enc := json.NewEncoder(os.Stdout)

	go func() {
		for {
			record, err := rd.Read()
			if err != nil {
				if err == ringbuf.ErrClosed {
					return
				}
				log.Printf("ring buffer read error: %v", err)
				continue
			}

			ev, err := parseEvent(record.RawSample)
			if err != nil {
				log.Printf("parse error: %v", err)
				continue
			}

			// Skip empty paths (kernel paths we couldn't resolve)
			if ev.FilePath == "" {
				continue
			}

			if err := enc.Encode(ev); err != nil {
				log.Printf("json encode error: %v", err)
			}
		}
	}()

	<-sig
	log.Println("ZeroCore eBPF probe shutting down")
}
